# Generated by Django 5.0.2 on 2026-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_in_progress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='scheduled_date',
            field=models.DateField(verbose_name='Επιθυμητή Ημερομηνία Ολοκλήρωσης'),
        ),
    ]
