# Generated by Django 5.0.2 on 2026-07-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_scheduledtask_scheduled_date'),
        ('accounts', '0008_item_status_shipped'),
    ]

    operations = []
