# Generated by Django 5.0.2 on 2026-08-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_item_status_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtaskitem',
            name='notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Σημειώσεις'),
        ),
    ]
