# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_reopen_tasks_awaiting_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtaskitem',
            name='item_status',
            field=models.CharField(
                choices=[
                    ('under_work', 'Υπό κατασκευή'),
                    ('skeleton_ready', 'Σκελετός Έτοιμος'),
                    ('reserved', 'Δεσμευμένο'),
                    ('completed', 'Ολοκληρώθηκε'),
                    ('shipped', 'Έχει αποσταλεί'),
                ],
                default='under_work',
                max_length=20,
                verbose_name='Κατάσταση προϊόντος',
            ),
        ),
    ]
