# Generated by Django 5.0.2 on 2026-07-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_task_stock_reservation'),
    ]

    operations = []
