# Generated by Django 5.0.2 on 2026-08-24 20:05

from django.db import migrations


def drop_discount_percent(apps, schema_editor):
    table = 'products_offeritem'
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table)
        ]
    if 'discount_percent' not in columns:
        return
    schema_editor.execute(f'ALTER TABLE {table} DROP COLUMN discount_percent')


def add_discount_percent(apps, schema_editor):
    table = 'products_offeritem'
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table)
        ]
    if 'discount_percent' in columns:
        return
    schema_editor.execute(
        f'ALTER TABLE {table} ADD COLUMN discount_percent decimal NOT NULL DEFAULT 0'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20260724_1409'),
    ]

    operations = [
        migrations.RunPython(drop_discount_percent, add_discount_percent),
    ]
