# Generated by Django 5.0.2 on 2026-08-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20260724_1409'),
        ('products', '0014_offeritem_discount_percent'),
    ]

    operations = []
