# Generated by Django 5.0.2 on 2026-08-24 20:25

import django.core.validators
from django.db import migrations, models


def _offeritem_columns(schema_editor):
    table = 'products_offeritem'
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table)
        }


def add_discount_percent(apps, schema_editor):
    if 'discount_percent' in _offeritem_columns(schema_editor):
        return
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE products_offeritem '
            'ADD COLUMN discount_percent numeric(5, 2) DEFAULT 0 NOT NULL'
        )
        return
    schema_editor.execute(
        'ALTER TABLE products_offeritem '
        'ADD COLUMN discount_percent decimal NOT NULL DEFAULT 0'
    )


def drop_discount_percent(apps, schema_editor):
    if 'discount_percent' not in _offeritem_columns(schema_editor):
        return
    schema_editor.execute('ALTER TABLE products_offeritem DROP COLUMN discount_percent')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_offeritem_discount_percent'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='offeritem',
                    name='discount_percent',
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='Έκπτωση (%)',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_discount_percent, drop_discount_percent),
            ],
        ),
    ]
