# Generated by Django 5.0.2 on 2026-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_offeritem_line_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hide_totals',
            field=models.BooleanField(default=False, verbose_name='Χωρίς εμφάνιση συνολικών ποσών'),
        ),
    ]
