# Generated by Django 5.0.2 on 2026-09-30 17:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_offer_hide_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ποσότητα'),
        ),
    ]
