# Generated by Django 5.0.2 on 2026-09-30 18:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_offeritem_decimal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Δεσμευμένη ποσότητα'),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='quantity_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσότητα Μετά'),
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='quantity_before',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσότητα Πριν'),
        ),
    ]
