# Generated by Django 5.0.2

from django.db import migrations, models


DEFAULT_COMPANY_SIGNATURE = (
    'Μετά τιμής,\n'
    '\n'
    'ΓΙΑ ΤΗΝ ΕΤΑΙΡΕΙΑ\n'
    '\n'
    'ΜΠΟΥΡΟΥ ΓΕΩΡΓΙΑ & ΣΙΑ Ε.Ε.\n'
    '\n'
    'Η ΕΚΠΡΟΣΩΠΟΣ\n'
    '\n'
    'ΜΠΟΥΡΟΥ ΓΕΩΡΓΙΑ'
)

DEFAULT_INDIVIDUAL_SIGNATURE = (
    'Μετά τιμής,\n'
    '\n'
    'ΓΙΑ ΤΗΝ ΕΤΑΙΡΕΙΑ\n'
    '\n'
    'ΜΠΟΥΡΟΥ ΓΕΩΡΓΙΑ\n'
    '\n'
    'Η ΕΚΠΡΟΣΩΠΟΣ\n'
    '\n'
    'ΜΠΟΥΡΟΥ ΓΕΩΡΓΙΑ'
)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productmaterial_decimal_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersettings',
            name='company_signature',
            field=models.TextField(
                blank=True,
                default=DEFAULT_COMPANY_SIGNATURE,
                verbose_name='Κείμενο Υπογραφής Εταιρίας',
            ),
        ),
        migrations.AddField(
            model_name='offersettings',
            name='individual_signature',
            field=models.TextField(
                blank=True,
                default=DEFAULT_INDIVIDUAL_SIGNATURE,
                verbose_name='Κείμενο Υπογραφής Ατομικής',
            ),
        ),
    ]
