# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_offersettings_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(
                choices=[('active', 'Ενεργή'), ('cancelled', 'Ακυρωμένη')],
                default='active',
                max_length=20,
                verbose_name='Κατάσταση',
            ),
        ),
    ]
